### PR TITLE
Update proxy.js

### PR DESCRIPTION
**Pull request by sudheergopalam**
I added caching logic to the passthrough code..please review and make necessary.. its works but not sure I implemented the right way.

### CODE REVIEW

**Comment by theganyo** [comment]
I'm confused as to why you would need this. The api key should already be cached per the settings in swagger.yaml. Indeed, when I run the app with DEBUG=oauth, I can see the following:

anubis:proxy sganyo$ DEBUG=oauth a127 project start
user config loaded from /Users/sganyo/.a127/config.js
user config loaded from /Users/sganyo/.a127/config.js
Starting: /Users/sganyo/temp/proxy/app.js...
  project started here: http://localhost:10010
  project will restart on changes.
  to restart at any time, enter `rs`
proxy started on port 10010
  oauth verifyApiKey: FbqTSasKukBPO3Gvrpi9797uuCRcq6A +0ms
  oauth cache miss: apiKey:FbqTSasKukBPO3Gvrpi9797uuCRcq6A +1ms
  oauth verifyApiKey: FbqTSasKukBPO3Gvrpi9797uuCRcq6A +1s
  oauth cache hit: apiKey:FbqTSasKukBPO3Gvrpi9797uuCRcq6A +1ms

Per the output (and as per a noticeable performance difference), my API Key is cached and returned as I hit endpoints. What are you seeing?

Scott

**Comment by sudheergopalam** [comment]
Does not seem to work for me. I am always seeing as cache miss.
Below is the debug log and curl command.
I updated the config/default.yaml to point target to proxyBase: http://weather.yahooapis.com
and cache expiry to : 9999999

Sudheer-Gopalam-2:passthrough-proxy-with-keyvalidation ApigeeCorporation$ DEBUG=oauth a127 project start
Starting: /Users/ApigeeCorporation/Documents/Apigee127/a127-samples/passthrough-proxy-with-keyvalidation/app.js...
  project started here: http://localhost:10010
  project will restart on changes.
  to restart at any time, enter `rs`
proxy started on port 10010
  oauth verifyApiKey: 48983274832784734091809401 +0ms
  oauth cache miss: apiKey:48983274832784734091809401 +1ms
  oauth verifyApiKey: 48983274832784734091809401 +7s
  oauth cache miss: apiKey:48983274832784734091809401 +1ms
  oauth verifyApiKey: 48983274832784734091809401 +7s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +8s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +11s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +9s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +24s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +5s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +5s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +8s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +2s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +6s
  oauth cache miss: apiKey:48983274832784734091809401 +0ms
  oauth verifyApiKey: 48983274832784734091809401 +4s
  oauth cache miss: apiKey:48983274832784734091809401 +1ms

CURL that I am using: curl -v http://localhost:10010/passthrough?api_key=48983274832784734091809401

**Comment by theganyo** [comment]
That's odd. Just curious: Is that a valid API Key? As currently implemented, the cache doesn't track invalid keys...

**Comment by sudheergopalam** [comment]
It's a valid API key as far as I know, I will give it another try once I am in office. Btw where can I find the implementation logic that caches only valid APIKey, Is it in one of the helper modules ?

**Comment by sudheergopalam** [comment]
Thanks Scott... You were right, it was an invalid API Key. Its working fine now.
If I want to enable a timeout feature for oAuth how can I do it? for instance if the oAuth verification call is taking more than x milliseconds to respond, ignore it and continue. Will I need to write code or I can do it using Swagger configuration?

**Comment by theganyo** [comment]
No, there is no configuration for that. The reason we added the verifyAPIKey function in the controller (instead of just configuring the Swagger for this) was to address your need for the proxy to allow any network error (and, actually, any error other than an invalid key) to be ignored. This would be a similar capability that you can just add to the verifyAPIKey function. Let me know if you need any help with that.

**Pull request closed without merging**
